### ISSUE TITLE
.NET lib sample

### ISSUE THREAD

**Issue by snitkjaer** [PKISolutions/ADCS-CertMod#1]
This looks really nice thanks for sharing!

Would you have a sample of a custom exit lib that can modify the CSR say for instance modify the request subject name or something like that?

Bo

**Comment by Crypt32** [comment]
First of all: exit modules cannot modify anything. They are intended for notifications only. Custom processing is part of policy module. Though this package provides policy module support.

Here is an example of policy module that uses this package: https://github.com/PKISolutions/ADCS-SID-Extension-Policy-Module

**Comment by snitkjaer** [comment]
Thanks for the quick reply, I will have a look at the policy module and the provide "sample"!

**Comment by Crypt32** [comment]
Please refer to #13 and [this](https://github.com/PKISolutions/ADCS-CertMod/releases/tag/v3.0.0-demo) release to get samples and compiled libs.
