### ISSUE TITLE
Useful CertSrvH constants is not available to the developer

### ISSUE THREAD

**Issue by phonexicum** [PKISolutions/ADCS-CertMod#4]
To properly use `ICertServerPolicyManaged.SetCertificateProperty` method, the `PropertyType` constant must be specified.
Currently those constants are stored in `CertSrvH` class at [CertSrvH.cs](https://github.com/PKISolutions/ADCS-CertMod/blob/f735ac1ba4185cffb7ef63bad34ccea26f2ab533/ADCS.CertMod.Managed/Extensions/CertSrvH.cs#L8), AND the class is not available.
On usage, the compiler retuns error: `CS0122: 'CertSrvH' is inaccessible due to its protection level`.

1. How do you feel about making the class public ?
2. How do you feel about changing CertSrvH class into CertSrvH enum ?
3. How do you feel about adding to documentation [here](https://www.pkisolutions.com/apidocs/certmod/html/M_ADCS_CertMod_Managed_ICertServerPolicyManaged_SetCertificateProperty.htm) notice, that not all properties can be changed, due to microsoft's restrictions: [ICertServerPolicy::SetCertificateProperty](https://learn.microsoft.com/en-us/windows/win32/api/certif/nf-certif-icertserverpolicy-setcertificateproperty#parameters)

**Comment by Crypt32** [comment]
> 2\. How do you feel about changing CertSrvH class into CertSrvH enum ?

positively, because it makes sense.

> 3\. How do you feel about adding to documentation [here](https://www.pkisolutions.com/apidocs/certmod/html/M_ADCS_CertMod_Managed_ICertServerPolicyManaged_SetCertificateProperty.htm) notice, that not all properties can be changed, due to microsoft's restrictions: [ICertServerPolicy::SetCertificateProperty](https://learn.microsoft.com/en-us/windows/win32/api/certif/nf-certif-icertserverpolicy-setcertificateproperty#parameters)

Link to corresponding Microsoft page is provided at the bottom:
![image](https://github.com/PKISolutions/ADCS-CertMod/assets/6384119/eae5223a-d5e6-4265-83b2-d559afa1ddf9)

isn't this sufficient?

**Comment by phonexicum** [comment]
> > 3. How do you feel about adding to documentation [here](https://www.pkisolutions.com/apidocs/certmod/html/M_ADCS_CertMod_Managed_ICertServerPolicyManaged_SetCertificateProperty.htm) notice, that not all properties can be changed, due to microsoft's restrictions: [ICertServerPolicy::SetCertificateProperty](https://learn.microsoft.com/en-us/windows/win32/api/certif/nf-certif-icertserverpolicy-setcertificateproperty#parameters)
> 
> Link to corresponding Microsoft page is provided at the bottom: ![image](https://private-user-images.githubusercontent.com/6384119/345773005-eae5223a-d5e6-4265-83b2-d559afa1ddf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDcyMDQsIm5iZiI6MTcyMDUwNjkwNCwicGF0aCI6Ii82Mzg0MTE5LzM0NTc3MzAwNS1lYWU1MjIzYS1kNWU2LTQyNjUtODNiMi1kNTU5YWZhMWRkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDYzNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjJkOTVhMzdlNGE1NTI1N2M2Y2JhMjRhZmQ2YTMzZjVjMzdiNTZjMzI4ZDA4NjAyN2RiZjNhZTM4N2NjNTE5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8uteIrwL_OjClm_6T1wvDJo5qqAvHHarg36seA-PzQA)
> 
> isn't this sufficient?

Oh, sorry, don't know how I missed it.

Thus, seems we agreed on points 1 and 2.

**Comment by Crypt32** [comment]
> Thus, seems we agreed on points 1 and 2.

yes, it makes sense to make it enum and public.
